apiVersion: batch/v1
kind: Job
metadata:
  genarateName: test-job-
  annotations:
    argocd.argoproj.io/hook: Sync
#    argocd.argoproj.io/hook-delete-policy: HookSucceeded
#BeforeHookCreation
spec:
  backoffLimit: 1
  completions: 1
  template:
    spec:
      containers:
      - name: jobtest
        image: busybox
        command: ["echo", "job-test"] 
      restartPolicy: Never
