apiVersion: batch/v1
kind: Job
metadata:
  name: jobtest
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  backoffLimit: 1
  completions: 1
  template:
    spec:
      containers:
      - name: jobtest
        image: 
          valueFrom:
            configMapKeyRef:
              name: docker-config
              key: image_name
       restartPolicy: Never
#        command: ["/bin/sh", "-c", "env"]
#        env:
#        - name: LOG_LEVEL
#          valueFrom:
#            configMapKeyRef:
#              name: env-config
#              key: log_level
#      restartPolicy: Never
