apiVersion: batch/v1
kind: Job
metadata:
  generateName: job-test-
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  backoffLimit: 1
  completions: 1
  template:
    spec:
      containers:
      - name: jobtest
        image: busybox
        command: ["sleep", "180"] 
      restartPolicy: Never

